# memory island game configuration file
#
# Actions: is the list of actions in the game
#
version: 1.0

Actions:
  Boil:
    image_file: assets/actions/Boil.png
    sound: assets\sounds\Kettle_Boiling_1s_Fade_In_Fade_Out.mp3
  Chop:
    image_file: assets/actions/Chop.png
    sound:
  Toast:
    image_file: assets/actions/Toaster.png
    sound:
      - assets\sounds\Toaster_In_1.2s_231119.mp3
      - assets\sounds\Toaster_Out_1s_231119.mp3
  Fry:
    sound:
  Slice:
    image_file:
    sound:

SoundEffect:
    Success:
      - assets\sounds\Pixabay\success-fanfare-trumpets-6185.mp3
    Fail:
      - assets\sounds\Pixabay\wah-wah-sad-trombone-6347.mp3

Music:
  PlayList: 
    - assets\music\Island_Cooking_Songs_LOOP2.mp3
    - assets\music\AABA_120bpm_3mn20s_ACIDIC_trim.mp3

Ingredients:
  Aubergine:
    image_file: assets/ingredients/Aubergine.png
    actions:
      - Fry
  Carrot:
    image_file: assets\ingredients\Carrot.png
    actions:
      - Boil

  Courgette:
    image_file: assets\ingredients\Courgette.png 
    actions:
      - Fry

  Garlic:
    image_file: assets\ingredients\Garlic.png   
    actions:
      - Fry        
        
  Potato:
    image_file: assets\ingredients\Potato.png
    actions:
      - Boil
        
  Bread:
    image_file: assets\ingredients\Bread.png      
    actions:
      - Slice

  Cheese:
    image_file: assets\ingredients\Cheese.png  
    actions:
      - Slice
        
  Egg:
    image_file: assets\ingredients\Egg.png        
    actions:
      - Boil
      - Fry
        
  Lettuce:
    image_file: assets\ingredients\Lettuce.png  
    actions:
      - Chop
        
  Tomato:
    # Need to get it to on unix
    #image_file: assets/ingredients/Tomato.png
    image_file: assets\ingredients\Tomato.png
    actions:
      - Chop
    

Recipes:
  Sandwich:
    - Bread
    - Toast
    - Lettuce
    - Chop
    - Tomato
    - Chop
    - Cheese
    - Chop
    - Bread
    - Toast
  Ratatouille:
    - Aubergine
    - Chop
    - Courgette
    - Chop
    - Pepper
    - Chop    
    - Tomato
    - Chop    
    - Garlic
    - Chop
    - Fry
    - Cook
    
      